import { error } from '@sveltejs/kit';
import index from '$lib/generated/llms/index.json';
import type { RequestHandler } from './$types';
import { docsFramework, markdownResponse } from '$lib/server/docs-framework';

// Query-selected representations must not be collapsed into one prerendered file.
export const prerender = false;

/**
 * The Markdown twin of a docs page: /docs/flow-grids.md serves the same content
 * as /docs/flow-grids, with the Svelte components rewritten into Markdown.
 * Generated by scripts/build-llms-docs.mjs.
 */
const files = import.meta.glob('$lib/generated/llms/pages/**/*.md', {
	query: '?raw',
	import: 'default',
	eager: true
}) as Record<string, string>;

const bySlug = new Map(index.pages.map((page) => [page.slug, page]));

export const GET: RequestHandler = ({ params, url }) => {
	const framework = docsFramework(url);
	const entry = bySlug.get(params.slug);
	if (!entry || (framework !== 'all' && entry.frameworks && !entry.frameworks.includes(framework)))
		error(404, 'Not found for this framework');
	const suffix = `/pages/${framework === 'all' ? '' : `${framework}/`}${entry.file}`;
	const markdown = files[Object.keys(files).find((path) => path.endsWith(suffix)) ?? ''];
	if (!markdown) error(404, 'Not found');

	return markdownResponse(markdown);
};
