import { error } from '@sveltejs/kit';
import index from '$lib/generated/llms/index.json';
import type { EntryGenerator, RequestHandler } from './$types';

export const prerender = true;

/**
 * The Markdown twin of a docs page: /docs/flow-grids.md serves the same content
 * as /docs/flow-grids, with the Svelte components rewritten into Markdown.
 * Generated by scripts/build-llms-docs.mjs.
 */
const files = import.meta.glob('$lib/generated/llms/pages/*.md', {
	query: '?raw',
	import: 'default',
	eager: true
}) as Record<string, string>;

const bySlug = new Map<string, string>(
	index.pages.map((page) => [
		page.slug,
		files[Object.keys(files).find((f) => f.endsWith(`/${page.file}`)) ?? ''] ?? ''
	])
);

export const entries: EntryGenerator = () => index.pages.map((page) => ({ slug: page.slug }));

export const GET: RequestHandler = ({ params }) => {
	const markdown = bySlug.get(params.slug);
	if (!markdown) error(404, 'Not found');

	return new Response(markdown, {
		headers: { 'content-type': 'text/markdown; charset=utf-8' }
	});
};
